In [1]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.10/dist-packages (0.22.0)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.10.1)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.22.4)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.5.3)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.2.2)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (3.7.1)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.3.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from mlxtend) (67.7.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.41.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.1.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24.2->mlxtend) (2022.7.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.0.2->mlxtend) (3.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [2]:
import mlxtend

In [3]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

In [4]:
book=pd.read_csv("/content/book.csv")
book

      ChildBks  YouthBks  CookBks  ...  ItalAtlas  ItalArt  Florence
0            0         1        0  ...          0        0         0
1            1         0        0  ...          0        0         0
2            0         0        0  ...          0        0         0
3            1         1        1  ...          0        0         0
4            0         0        1  ...          0        0         0
...        ...       ...      ...  ...        ...      ...       ...
1995         0         0        1  ...          0        1         1
1996         0         0        0  ...          0        0         0
1997         0         0        0  ...          0        0         0
1998         0         0        1  ...          0        0         0
1999         0         0        0  ...          0        0         0

[2000 rows x 11 columns]

In [5]:
book['ChildBks'].value_counts()

0    1154
1     846
Name: ChildBks, dtype: int64

In [6]:
book['YouthBks'].value_counts()

0    1505
1     495
Name: YouthBks, dtype: int64

In [7]:
book['CookBks'].value_counts()

0    1138
1     862
Name: CookBks, dtype: int64

In [8]:
book['DoItYBks'].value_counts()

0    1436
1     564
Name: DoItYBks, dtype: int64

In [9]:
book['RefBks'].value_counts()

0    1571
1     429
Name: RefBks, dtype: int64

In [10]:
book['ArtBks'].value_counts()

0    1518
1     482
Name: ArtBks, dtype: int64

In [12]:
book['GeogBks'].value_counts()

0    1448
1     552
Name: GeogBks, dtype: int64

In [13]:
book['ItalCook'].value_counts()

0    1773
1     227
Name: ItalCook, dtype: int64

In [14]:
book['ItalAtlas'].value_counts()

0    1926
1      74
Name: ItalAtlas, dtype: int64

In [16]:
book['ItalArt'].value_counts()

0    1903
1      97
Name: ItalArt, dtype: int64

In [17]:
book['Florence'].value_counts()

0    1783
1     217
Name: Florence, dtype: int64

# pre processing

In [18]:
df=pd.get_dummies(book)
df.head()

   ChildBks  YouthBks  CookBks  ...  ItalAtlas  ItalArt  Florence
0         0         1        0  ...          0        0         0
1         1         0        0  ...          0        0         0
2         0         0        0  ...          0        0         0
3         1         1        1  ...          0        0         0
4         0         0        1  ...          0        0         0

[5 rows x 11 columns]

# apriori algorithm

In [19]:
ferquent_itemsets= apriori(df,min_support=0.1,use_colnames=True)
ferquent_itemsets

    support                       itemsets
0    0.4230                     (ChildBks)
1    0.2475                     (YouthBks)
2    0.4310                      (CookBks)
3    0.2820                     (DoItYBks)
4    0.2145                       (RefBks)
5    0.2410                       (ArtBks)
6    0.2760                      (GeogBks)
7    0.1135                     (ItalCook)
8    0.1085                     (Florence)
9    0.1650           (YouthBks, ChildBks)
10   0.2560            (CookBks, ChildBks)
11   0.1840           (DoItYBks, ChildBks)
12   0.1515             (RefBks, ChildBks)
13   0.1625             (ArtBks, ChildBks)
14   0.1950            (GeogBks, ChildBks)
15   0.1620            (CookBks, YouthBks)
16   0.1155           (DoItYBks, YouthBks)
17   0.1010             (ArtBks, YouthBks)
18   0.1205            (GeogBks, YouthBks)
19   0.1875            (DoItYBks, CookBks)
20   0.1525              (CookBks, RefBks)
21   0.1670              (ArtBks, CookBks)
22   0.1925             (GeogBks, CookBks)
23   0.1135            (CookBks, ItalCook)
24   0.1055             (DoItYBks, RefBks)
25   0.1235             (DoItYBks, ArtBks)
26   0.1325            (GeogBks, DoItYBks)
27   0.1105              (GeogBks, RefBks)
28   0.1275              (GeogBks, ArtBks)
29   0.1290  (CookBks, YouthBks, ChildBks)
30   0.1460  (DoItYBks, CookBks, ChildBks)
31   0.1225    (CookBks, RefBks, ChildBks)
32   0.1265    (ArtBks, CookBks, ChildBks)
33   0.1495   (GeogBks, CookBks, ChildBks)
34   0.1045  (GeogBks, DoItYBks, ChildBks)
35   0.1020    (GeogBks, ArtBks, ChildBks)
36   0.1015    (ArtBks, DoItYBks, CookBks)
37   0.1085   (GeogBks, DoItYBks, CookBks)
38   0.1035     (ArtBks, CookBks, GeogBks)

In [20]:
rules = association_rules(ferquent_itemsets,metric="lift", min_threshold=0.7)
rules
rules.sort_values('lift',ascending=False)[0:20]

            antecedents          consequents  ...  conviction  zhangs_metric
28            (CookBks)           (ItalCook)  ...    1.203406       1.000000
29           (ItalCook)            (CookBks)  ...         inf       0.641850
78   (ArtBks, ChildBks)            (GeogBks)  ...    1.944628       0.669008
79            (GeogBks)   (ArtBks, ChildBks)  ...    1.328448       0.773887
85             (ArtBks)  (DoItYBks, CookBks)  ...    1.403674       0.730966
84  (DoItYBks, CookBks)             (ArtBks)  ...    1.654797       0.682834
99            (GeogBks)    (ArtBks, CookBks)  ...    1.332800       0.766114
94    (ArtBks, CookBks)            (GeogBks)  ...    1.904063       0.665866
97             (ArtBks)   (GeogBks, CookBks)  ...    1.415327       0.726961
96   (GeogBks, CookBks)             (ArtBks)  ...    1.641657       0.683298
53  (CookBks, ChildBks)             (RefBks)  ...    1.506277       0.741584
56             (RefBks)  (CookBks, ChildBks)  ...    1.734652       0.702405
77  (GeogBks, ChildBks)             (ArtBks)  ...    1.591452       0.669894
80             (ArtBks)  (GeogBks, ChildBks)  ...    1.395719       0.710494
86           (DoItYBks)    (ArtBks, CookBks)  ...    1.301418       0.746546
83    (ArtBks, CookBks)           (DoItYBks)  ...    1.830626       0.643481
67            (GeogBks)  (CookBks, ChildBks)  ...    1.623273       0.728432
66  (CookBks, ChildBks)            (GeogBks)  ...    1.740319       0.708850
90  (DoItYBks, CookBks)            (GeogBks)  ...    1.718354       0.643743
91            (GeogBks)  (DoItYBks, CookBks)  ...    1.338806       0.722433

[20 rows x 10 columns]

In [21]:
rules[rules.lift>1]

           antecedents         consequents  ...  conviction  zhangs_metric
0           (YouthBks)          (ChildBks)  ...    1.731000       0.485714
1           (ChildBks)          (YouthBks)  ...    1.233750       0.633449
2            (CookBks)          (ChildBks)  ...    1.421069       0.505870
3           (ChildBks)           (CookBks)  ...    1.441240       0.498856
4           (DoItYBks)          (ChildBks)  ...    1.660347       0.489842
..                 ...                 ...  ...         ...            ...
95   (GeogBks, ArtBks)           (CookBks)  ...    3.022812       0.537602
96  (GeogBks, CookBks)            (ArtBks)  ...    1.641657       0.683298
97            (ArtBks)  (GeogBks, CookBks)  ...    1.415327       0.726961
98           (CookBks)   (GeogBks, ArtBks)  ...    1.148237       0.824355
99           (GeogBks)   (ArtBks, CookBks)  ...    1.332800       0.766114

[100 rows x 10 columns]

In [22]:
#Movies
movies=pd.read_csv("/content/my_movies.csv")
movies

              V1             V2             V3  ... LOTR Braveheart  Green Mile
0    Sixth Sense          LOTR1  Harry Potter1  ...    0          0           1
1      Gladiator        Patriot     Braveheart  ...    0          1           0
2          LOTR1          LOTR2            NaN  ...    0          0           0
3      Gladiator        Patriot    Sixth Sense  ...    0          0           0
4      Gladiator        Patriot    Sixth Sense  ...    0          0           0
5      Gladiator        Patriot    Sixth Sense  ...    0          0           0
6  Harry Potter1  Harry Potter2            NaN  ...    0          0           0
7      Gladiator        Patriot            NaN  ...    0          0           0
8      Gladiator        Patriot    Sixth Sense  ...    0          0           0
9    Sixth Sense           LOTR      Gladiator  ...    1          0           1

[10 rows x 15 columns]

In [23]:
movies['V1'].value_counts()

Gladiator        6
Sixth Sense      2
LOTR1            1
Harry Potter1    1
Name: V1, dtype: int64

In [24]:
movies['V2'].value_counts()

Patriot          6
LOTR1            1
LOTR2            1
Harry Potter2    1
LOTR             1
Name: V2, dtype: int64

In [25]:
movies['V3'].value_counts()

Sixth Sense      4
Harry Potter1    1
Braveheart       1
Gladiator        1
Name: V3, dtype: int64

In [31]:
movies['V4'].value_counts()

Green Mile    2
Name: V4, dtype: int64

In [32]:
movies['V5'].value_counts()

LOTR2    1
Name: V5, dtype: int64

In [26]:
movies['Sixth Sense'].value_counts()

1    6
0    4
Name: Sixth Sense, dtype: int64

In [33]:
movies['Gladiator'].value_counts()

1    7
0    3
Name: Gladiator, dtype: int64

In [34]:
movies['LOTR1'].value_counts()

0    8
1    2
Name: LOTR1, dtype: int64

In [35]:
movies['Harry Potter1'].value_counts()

0    8
1    2
Name: Harry Potter1, dtype: int64

# Pre processing

In [36]:
df=pd.get_dummies(movies)
df.head()

   Sixth Sense  Gladiator  LOTR1  ...  V3_Sixth Sense  V4_Green Mile  V5_LOTR2
0            1          0      1  ...               0              1         1
1            0          1      0  ...               0              0         0
2            0          0      1  ...               0              0         0
3            1          1      0  ...               1              0         0
4            1          1      0  ...               1              0         0

[5 rows x 25 columns]

# apriori algorithm

In [37]:
ferquent_itemsets= apriori(df,min_support=0.1,use_colnames=True)
ferquent_itemsets

      support                                           itemsets
0         0.6                                      (Sixth Sense)
1         0.7                                        (Gladiator)
2         0.2                                            (LOTR1)
3         0.2                                    (Harry Potter1)
4         0.6                                          (Patriot)
...       ...                                                ...
1392      0.1  (Sixth Sense, V5_LOTR2, V2_LOTR1, V3_Harry Pot...
1393      0.1  (Sixth Sense, V5_LOTR2, V2_LOTR1, LOTR2, V3_Ha...
1394      0.1  (Sixth Sense, V5_LOTR2, V2_LOTR1, LOTR2, V3_Ha...
1395      0.1  (V5_LOTR2, V2_LOTR1, LOTR2, V3_Harry Potter1, ...
1396      0.1  (Sixth Sense, V5_LOTR2, V2_LOTR1, LOTR2, V3_Ha...

[1397 rows x 2 columns]

In [38]:
rules = association_rules(ferquent_itemsets,metric="lift", min_threshold=0.7)
rules
rules.sort_values('lift',ascending=False)[0:20]

                                             antecedents  ... zhangs_metric
32126  (Sixth Sense, V3_Harry Potter1, Harry Potter1,...  ...           1.0
33437              (LOTR2, Harry Potter1, V4_Green Mile)  ...           1.0
33415                        (Sixth Sense, LOTR2, LOTR1)  ...           1.0
33416                (Sixth Sense, LOTR2, V4_Green Mile)  ...           1.0
33417                (Sixth Sense, Harry Potter1, LOTR1)  ...           1.0
33418        (Sixth Sense, Harry Potter1, V4_Green Mile)  ...           1.0
33419                (Sixth Sense, LOTR1, V4_Green Mile)  ...           1.0
33420                        (LOTR2, V5_LOTR2, V2_LOTR1)  ...           1.0
33421                (V5_LOTR2, Harry Potter1, V2_LOTR1)  ...           1.0
33422                        (V5_LOTR2, LOTR1, V2_LOTR1)  ...           1.0
33423                (V5_LOTR2, V2_LOTR1, V4_Green Mile)  ...           1.0
33424                   (LOTR2, V5_LOTR2, Harry Potter1)  ...           1.0
33425                           (LOTR2, V5_LOTR2, LOTR1)  ...           1.0
33426                   (LOTR2, V5_LOTR2, V4_Green Mile)  ...           1.0
33427                   (V5_LOTR2, Harry Potter1, LOTR1)  ...           1.0
33428           (V5_LOTR2, Harry Potter1, V4_Green Mile)  ...           1.0
33429                   (V5_LOTR2, LOTR1, V4_Green Mile)  ...           1.0
33430                   (LOTR2, Harry Potter1, V2_LOTR1)  ...           1.0
33431                           (LOTR2, LOTR1, V2_LOTR1)  ...           1.0
33432                   (LOTR2, V2_LOTR1, V4_Green Mile)  ...           1.0

[20 rows x 10 columns]

In [39]:
rules[rules.lift>1]

            antecedents  ... zhangs_metric
0         (Sixth Sense)  ...      0.400000
1           (Gladiator)  ...      0.533333
6             (Patriot)  ...      0.250000
7         (Sixth Sense)  ...      0.250000
10        (Sixth Sense)  ...      1.000000
...                 ...  ...           ...
64247   (Harry Potter1)  ...      1.000000
64248           (LOTR1)  ...      1.000000
64249      (Green Mile)  ...      1.000000
64250  (V1_Sixth Sense)  ...      1.000000
64251   (V4_Green Mile)  ...      1.000000

[64202 rows x 10 columns]